# Generated by Django 3.2.9 on 2024-02-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_name_menu_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='url',
        ),
        migrations.AddField(
            model_name='menu',
            name='slug',
            field=models.SlugField(default='default-slug-value', max_length=255, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
